### ISSUE TITLE
Value for published is displayed in input-field

### ISSUE THREAD

**Issue by d-koppenhagen** [angular-buch/book-monkey2#10]
If we want to edit an existing book the value for `published` is currently not displayed in the corresponding input filed.
![bildschirmfoto 2016-10-09 um 14 41 35](https://cloud.githubusercontent.com/assets/4279702/19220503/989276e6-8e2e-11e6-856f-3690a7e8e90f.png)

**Comment by JohannesHoppe** [comment]
default behaviour. "useValueAsDate" has to be applied everywhere
