### ISSUE TITLE
Validation fails by edit a book

### ISSUE THREAD

**Issue by d-koppenhagen** [angular-buch/book-monkey2#11]
If we want to edit a book the validation takes no effect right now.
Using the "normal" form without any init-values, the validation works fine.

**Comment by JohannesHoppe** [comment]
template driven or reactive?

**Comment by d-koppenhagen** [comment]
reactive

**Comment by d-koppenhagen** [comment]
fixes in 1c6bf62d6a9660091fb2a042323fe56a4d28e99c
