### ISSUE TITLE
Validation of authors fails

### ISSUE THREAD

**Issue by d-koppenhagen** [angular-buch/book-monkey2#12]
The validation of the authors fails right now in reactive forms example. This happens in edit and in create mode.

**Comment by d-koppenhagen** [comment]
Note:
this would help to validate each authors field:

```
  buildAuthorsArray(authors): FormArray {
    this.authors = this.fb.array(
        authors.map(a => this.fb.control(a, Validators.required)), Validators.required
    );
    return this.authors;
  }
```

The problem is just that an error will occur because of the error handling in `updateErrorMessages` -> there is no separate handling for each array field. @JohannesHoppe  any suggestions?

**Comment by JohannesHoppe** [comment]
Yes. :-)
`ErrorMessage.forControl` is not only a simple string, matching a FormControl-Name. It must support some kind of selector. Maybe a CSS selector or just some kind of wildcards.

**Comment by d-koppenhagen** [comment]
closed by https://github.com/angular-buch/book-monkey2/commit/93fde7c48c28f0177e818e1caf3bc15d4e828f52
