### ISSUE TITLE
TSLint doesn't like for (... in ...) without if-filter

### ISSUE THREAD

**Issue by d-koppenhagen** [angular-buch/book-monkey2#13]
TSLint grouses about this:

```
updateErrorMessages() {
    for (let field in this.validation) {
      this.validation[field].error = '';
      let control = this.myForm.get(field);

      if (control && control.dirty && control.invalid) {
        for (let key in control.errors) {
          this.validation[field].error = this.validation[field].messages[key];
        }
      }
    };
  }
```

TSLInt: `for (... in ...) statements must be filtered with an if statement`.

Does anybody know a better solution for the whole code-block? 
@GregOnNet @fmalcher @JohannesHoppe

**Comment by d-koppenhagen** [comment]
Ahhh... there is an open issue: https://github.com/palantir/tslint/issues/1301

**Comment by JohannesHoppe** [comment]
I will try to find a better solution now...

**Comment by JohannesHoppe** [comment]
`Object.keys(XXX).forEach` would be akward, too.
But we are save to use `for...of` instead if `for...in:
https://basarat.gitbooks.io/typescript/content/docs/for...of.html

The research continues...

**Comment by d-koppenhagen** [comment]
@JohannesHoppe fixed this ;-)

**Comment by melodyJie** [comment]
for (const field in this.formErrors) {
  if (this.formErrors.hasOwnProperty(field)) {


Is that how you solved it?

**Comment by GregOnNet** [comment]
Hey @melodyJie ,

thanks for your question.
You will find the final version collecting errors for each control here: https://github.com/angular-buch/book-monkey2/blob/master/src/app/book-monkey/iteration-4/reactive-forms/book-form/book-form.component.ts#L104

**Comment by tomoat** [comment]
use ```for...of```

**Comment by Kotomanga** [comment]
@tomoat `for ... of` not work with `Object`, just for `Array`

**Comment by SilicorniO** [comment]
> @tomoat `for ... of` not work with `Object`, just for `Array`

Try for ... of Object.keys( YOUR_OBJECT )
