### ISSUE TITLE
build is broken 😕

### ISSUE THREAD

**Issue by fmalcher** [angular-buch/book-monkey2#16]
Build for `iteration-2-navigation` fails with strange error...
see https://travis-ci.org/angular-buch/book-monkey2/jobs/175577742

**Comment by JohannesHoppe** [comment]
as agreed, low prio since only one monkey fails

**Comment by d-koppenhagen** [comment]
okay with the last commit all monkey build failed https://travis-ci.org/angular-buch/book-monkey2 .
I updated the environment - angular-cli, dependet packages, etc. (https://github.com/angular-buch/book-monkey2/commit/6275a7f3be9df58fe6b69d06ea40e56d30e9c15c)

**Comment by JohannesHoppe** [comment]
hmmm... you even did that `npm i -g angular-cli@1.0.0-beta.20-4``...
I don't see the error!

**Comment by JohannesHoppe** [comment]
that's the reason:
https://github.com/angular-buch/angular-cli-ghpages/blob/master/deploy.js#L9

Internal Angular-CLI API has changed again...

**Comment by JohannesHoppe** [comment]
uff, wasn scheiss: https://github.com/angular-buch/angular-cli-ghpages/issues/2
