### ISSUE TITLE
Template driven form can't be compiled via AOT

### ISSUE THREAD

**Issue by JohannesHoppe** [angular-buch/book-monkey2#17]
See https://book-monkey2.angular-buch.com/iteration-4/template-driven-forms/admin

```
git clone git@github.com:book-monkey2-build/iteration-4-template-driven-forms.git
cd iteration-4-template-driven-forms
ng build --prod --aot
```

Issue: 
> error_handler.js:47 EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'registerControl' of null
> TypeError: Cannot read property 'registerControl' of null

Reason:
https://github.com/angular-buch/book-monkey2/blob/master/src/app/book-monkey/iteration-4/template-driven-forms/book-form/book-form.component.html#L66
` ngModelGroup="thumbnail"` and `name="url"` are somehow colliding, when executing this code:
https://github.com/angular/angular/blob/45ddd6ba78b5c9a6994b800f77a0499abb5b9b1a/modules/%40angular/forms/src/directives/ng_form.ts#L93

```
    NgForm.prototype.addControl = function (dir) {
        var _this = this;
        resolvedPromise.then(function () {
            var container = _this._findContainer(dir.path); // <--- path has "url / thumbnail" --> container goes null
            dir._control = container.registerControl(dir.name, dir.control); // <--- BOOOM!
            setUpControl(dir.control, dir);
            dir.control.updateValueAndValidity({ emitEvent: false });
        });
    };
```

**Comment by fmalcher** [comment]
Fixed by magic! 🍩

**Comment by JohannesHoppe** [comment]
Öhm.. geil?!?
