### ISSUE TITLE
Broken errorHandler for book-store.service

### ISSUE THREAD

**Issue by diverent2** [angular-buch/book-monkey2#21]
# BUG: BM-2 uses an outdated errorHandler for the book-store.service.ts

## Description

An error handler was introduced in iteration 3 (http)
It is currently using the outdated throw() function which will not throw the desired API-Call error, nor a code-error in VS-Code while compiling.
However it will throw a console error in the dev-tools:

``` console
core.js:14597 ERROR TypeError: rxjs__WEBPACK_IMPORTED_MODULE_3__.Observable.throw is not a function
    at CatchSubscriber.push../src/app/shared/book-store.service.ts.BookStoreService.errorHandler [as selector] (book-store.service.ts:37)
    at 
```

> You can test it by turning off your internet connection.

### 👎Current Implementation (outdated)

```typescript
  private errorHandler(error: Error | any): Observable<any> {
    return Observable.throw(error);
  }

```

see [Iteration 3](https://github.com/book-monkey2-build/iteration-3-http/blob/master/src/app/shared/book-store.service.ts) and the corresponding book (1st reprinted edition) on page 178/179 

### 👍 Correct Implementation

```typescript
  private errorHandler(error: Error | any): Observable<any> {
    return throwError(error);
  }
```

Source for the issue: [Issue 3733 on Rxjs](https://github.com/ReactiveX/rxjs/issues/3733)
I´ve also checked your update [blog posts](https://angular-buch.com/blog) but couldn´t find a note about this change. (should be added if possible imo)

Hope this gets fixed soon, it caused quite some confusion. :/

Best Regards
Diverent2 aka Maxi 😄

**Comment by fmalcher** [comment]
Danke für den Hinweis! Der Code auf dem `master`-Branch ist unverändert zum Buch, denn gedruckter Text ist geduldig. ;-) Auf dem Branch `ng6` findest Du allerdings die aktualisierte Variante des Projekts. Dort verwenden wir natürlich auch die "neue" Funktion `throwError()`: https://github.com/angular-buch/book-monkey2/blob/ng6/src/app/book-monkey/iteration-3/rxjs/shared/book-store.service.ts#L65
