### ISSUE TITLE
Ordnerstruktur BookMonkey

### ISSUE THREAD

**Issue by JohannesHoppe** [angular-buch/book-monkey2#3]
siehe https://github.com/Angular2Buch/book-monkey2/commit/4f3620cc3c8e7a1f00abc6f9143f0f8340646fb7#commitcomment-17115973

https://github.com/Angular2Buch/book-monkey2/commit/62cf81549e29cdd190d4c8638910fb689c21be3e#commitcomment-17130112

Das Problem liegt schon in der grundsätzlichen Einbindung:

``` js
import {BookListSimpleComponent} from './book-list-simple/book-list-simple.component';
import {BookListComponent} from './book-list/book-list.component';

// oder später dann 
import {HttpApp} from './http/http.component';
```

(siehe https://github.com/Angular2Buch/book-monkey2/blob/refactoring_it1/src/client/app/book-monkey/iteration-1/iteration-1.component.ts)

das geht so nicht. Der BookMonkey wird doch einfach nur weiter entwickelt und bekommt nicht ständig einen neuen Namen!?!
Daher lieber so:

``` js
import {BookListComponent as BookListComponent1} from './book-list/book-list.component';
import {BookListComponent as BookListComponent2} from './book-list-refactored/book-list.component';

// oder später dann
import {BookListComponent as BookListComponentXX} from './http/book-list.component';
```

Das bedeutet, das am Ende tatsächlich immer die `BookListComponent` eingebunden wird.
**Sofern BookList unsere "Startseite" sein soll.**  @GregOnNet @d-koppenhagen, @fmalcher

Alle Verzeichnisse gleichen sich dann mehr oder weniger und auch der Graph sollte besser ausschauen.
### Ich wäre ja zusätzlich noch dafür, die "Home" as startseite wieder einzuführen!
# TODO @JohannesHoppe

Ich bin gerade dabei, das mal für iteration1 gerade zu ziehen:
https://github.com/Angular2Buch/book-monkey2/tree/refactoring_it1

**Comment by fmalcher** [comment]
Hmm, meine Intention war, dass der BoomMonkey in jeder Iteration einen neuen Namen bekommt: HttpApp, PipesApp, DirectivesApp, ... (Eben weil es ja nicht immer "BookMonkey" sein kann).
Die Buchliste als Startseite zu nehmen, würde doch das ganze Routing aufbrechen?
Letztendlich ist es egal, also es geht jeder Weg.
Mir wäre aber wichtig, dass wir nicht alle Kapitel umschreiben müssen, weil wir schon wieder die Struktur geändert haben :smirk:

**Comment by JohannesHoppe** [comment]
Ja, das mit `BookList` war blödsinn. Später löst sich das Problem ja auf. Und alle Beispiele sind konsistent. Es müsste nur der Anfang in It1 etwass aufgeräumt werden.

Viel Wind um Nichts... =)
