### ISSUE TITLE
Changes for mini monkeys

### ISSUE THREAD

**Issue by fmalcher** [angular-buch/book-monkey2#4]
Updated:
We now have _one_ `app.module.ts` per mini app, see [here](https://github.com/Angular2Buch/book-monkey2/blob/master/src/app/book-monkey/iteration-2/navigation/app.module.ts). To make mini monkeys work, change the following:
- Uncomment three lines (in above example: 1, 12, 24) and delete the line below each
- delete `app-routing.module.1`

---

~~To extract the mini monkeys you'll need to change (each scoped to a single mini app):~~
- ~~`app.routing.ts`~~
  - ~~replace `RouterModule.forChild` with `RouterModule.forRoot`~~
- ~~`app.module.ts`~~
  - ~~replace line 1: `import { CommonModule } from '@angular/common';`~~
    - ~~with `import { BrowserModule } from '@angular/platform-browser';`~~
  - ~~replace module import `CommonModule` with `BrowserModule`~~
- ~~(optional) Remove `default` in `export default class AppModule { }`~~

**Comment by fmalcher** [comment]
"Everything" is different now after 57adf40319aea56d 😄 
Let's talk @JohannesHoppe

**Comment by fmalcher** [comment]
And updated again: d21b04439d6b2 😉  Should be final now.
@JohannesHoppe

**Comment by fmalcher** [comment]
Finished 🎉 :shipit:

**Comment by JohannesHoppe** [comment]
👍 :shipit:
