### ISSUE TITLE
Thumbnails of books are not shown

### ISSUE THREAD

**Issue by GregOnNet** [angular-buch/book-monkey2#6]
## Steps to reproduce
- Start development server
- Visit http://localhost:4200/iteration-4/http/books
## Actual Behavior

![image](https://cloud.githubusercontent.com/assets/444278/19125069/f9d43d28-8b35-11e6-959e-b5fece88fe02.png)
## Expected behavior

For each book a thumbnail is shown.

**Comment by GregOnNet** [comment]
@JohannesHoppe 

It seems that the API does not pass the `thumbnails`-property when `bookstoreService.getAll()` is called.
Can you enhance the API to deliver the needed data?

## Proposal

In my opinion the best design would be to pass a single thumbnail for a book instead of passing a list.
This makes the binding easier in the template.

``` json
{
  "title": "Angular 2",
  "thumbnail": "http://some-url.com"
}
```

## Reponse on `getAll`

![image](https://cloud.githubusercontent.com/assets/444278/19125511/994ce304-8b37-11e6-9364-e052f3e890a1.png)

**Comment by GregOnNet** [comment]
@JohannesHoppe @d-koppenhagen @fmalcher 

Using State-Safe-Operator for a [src]-Property has no effect.
It simply makes the template engine not to throw an error.
When `thumbnails` has no values simply `null` is set as value.
Even if the Array does not exist the image tag gets rendered.

``` html
<img class="ui tiny image" [src]="book?.thumbnails && book?.thumbnails[0]?.url">
```

The following condition works

``` html
<p *ngIf="book.thumbnails == undefined">No Thumb!</p>
```

**Comment by fmalcher** [comment]
ACK'd. 🙂

**Comment by d-koppenhagen** [comment]
Is this fixed now? I have taken over the changes made by @GregOnNet to all iterations/steps (see: 038ffabcca339a67e30fa4e301ec091b8524955b).

**Comment by JohannesHoppe** [comment]
I would vote for removing all state-save operators and fix the API to never return bogus data!

**Comment by JohannesHoppe** [comment]
and never, ever do this: `book.thumbnails == undefined`
check for falsy values like this: `!book.thumbnails`

**Comment by JohannesHoppe** [comment]
If data comes back correctly, we could go for:

``` html
<img class="ui tiny image" *ngIf="book.length" [src]="book.thumbnails[0].url">
```

**Comment by JohannesHoppe** [comment]
Having a single thumbnail would be even easier, but then we would need to change a lot of places in the book. Don't we?

**Comment by d-koppenhagen** [comment]
I agree with Johannes. It would be more complicated because if we store a new book we just have an array of books. This means that we should define the "main-Thumbnail".
Couldn't the API return an thumbnail[0] anyway with an placeholder Thumbnail? So if a user decides to create a new book without any thumbnail the API adds a thumbnail to an empty image or an image placeholer (eg. like [this](https://www.rulistings.com/Content/PlaceholderIcons/book_placeholder.png))

**Comment by JohannesHoppe** [comment]
Good idea. This would be consistent to the implementation of book.empty() which always has an empty author, too!

**Comment by d-koppenhagen** [comment]
@JohannesHoppe - ich habe jetzt ein default-Thumbnail hochgeladen (https://github.com/angular-buch/angular-buch.github.io/commit/a655c618dbbd3744f85e1216d52ed7f6e518f96d) und lasse dan Link dazu ausliefern, sofern kein anderes Bild im Thumbnails-Array ist (https://github.com/angular-buch/book-monkey2-api/commit/7006adb61d5e057cb49c1159489fb811ad84e04a).
Kannst du dafür sorgen, dass auf https://book-monkey2-api.angular-buch.com/ die aktuelle API-Version ausgeliefert wird (v0.2.4)?

**Comment by JohannesHoppe** [comment]
auto-deploy! abwarten :-)
